export const monthsShort = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];

export const productTypes = [
  "Mobile App",
  "Website",
  "Game",
  "Gadget"
]

export const monthsLong = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

export const genders = ["male", "female", "other"];

export const countries = [
  { code: "AW", value: "Aruba" },
  { code: "AF", value: "Afghanistan" },
  { code: "AO", value: "Angola" },
  { code: "AI", value: "Anguilla" },
  { code: "AX", value: "Åland Islands" },
  { code: "AL", value: "Albania" },
  { code: "AD", value: "Andorra" },
  { code: "AE", value: "United Arab Emirates" },
  { code: "AR", value: "Argentina" },
  { code: "AM", value: "Armenia" },
  { code: "AS", value: "American Samoa" },
  { code: "AQ", value: "Antarctica" },
  { code: "TF", value: "French Southern Territories" },
  { code: "AG", value: "Antigua and Barbuda" },
  { code: "AU", value: "Australia" },
  { code: "AT", value: "Austria" },
  { code: "AZ", value: "Azerbaijan" },
  { code: "BI", value: "Burundi" },
  { code: "BE", value: "Belgium" },
  { code: "BJ", value: "Benin" },
  { code: "BQ", value: "Bonaire, Sint Eustatius and Saba" },
  { code: "BF", value: "Burkina Faso" },
  { code: "BD", value: "Bangladesh" },
  { code: "BG", value: "Bulgaria" },
  { code: "BH", value: "Bahrain" },
  { code: "BS", value: "Bahamas" },
  { code: "BA", value: "Bosnia and Herzegovina" },
  { code: "BL", value: "Saint Barthélemy" },
  { code: "BY", value: "Belarus" },
  { code: "BZ", value: "Belize" },
  { code: "BM", value: "Bermuda" },
  { code: "BO", value: "Bolivia" },
  { code: "BR", value: "Brazil" },
  { code: "BB", value: "Barbados" },
  { code: "BN", value: "Brunei Darussalam" },
  { code: "BT", value: "Bhutan" },
  { code: "BV", value: "Bouvet Island" },
  { code: "BW", value: "Botswana" },
  { code: "CF", value: "Central African Republic" },
  { code: "CA", value: "Canada" },
  { code: "CC", value: "Cocos (Keeling) Islands" },
  { code: "CH", value: "Switzerland" },
  { code: "CL", value: "Chile" },
  { code: "CN", value: "China" },
  { code: "CI", value: "Côte d'Ivoire" },
  { code: "CM", value: "Cameroon" },
  { code: "CD", value: "Congo, The Democratic Republic of the" },
  { code: "CG", value: "Congo" },
  { code: "CK", value: "Cook Islands" },
  { code: "CO", value: "Colombia" },
  { code: "KM", value: "Comoros" },
  { code: "CV", value: "Cabo Verde" },
  { code: "CR", value: "Costa Rica" },
  { code: "CU", value: "Cuba" },
  { code: "CW", value: "Curaçao" },
  { code: "CX", value: "Christmas Island" },
  { code: "KY", value: "Cayman Islands" },
  { code: "CY", value: "Cyprus" },
  { code: "CZ", value: "Czechia" },
  { code: "DE", value: "Germany" },
  { code: "DJ", value: "Djibouti" },
  { code: "DM", value: "Dominica" },
  { code: "DK", value: "Denmark" },
  { code: "DO", value: "Dominican Republic" },
  { code: "DZ", value: "Algeria" },
  { code: "EC", value: "Ecuador" },
  { code: "EG", value: "Egypt" },
  { code: "ER", value: "Eritrea" },
  { code: "EH", value: "Western Sahara" },
  { code: "ES", value: "Spain" },
  { code: "EE", value: "Estonia" },
  { code: "ET", value: "Ethiopia" },
  { code: "FI", value: "Finland" },
  { code: "FJ", value: "Fiji" },
  { code: "FK", value: "Falkland Islands (Malvinas)" },
  { code: "FR", value: "France" },
  { code: "FO", value: "Faroe Islands" },
  { code: "FM", value: "Micronesia, Federated States of" },
  { code: "GA", value: "Gabon" },
  { code: "GB", value: "United Kingdom" },
  { code: "GE", value: "Georgia" },
  { code: "GG", value: "Guernsey" },
  { code: "GH", value: "Ghana" },
  { code: "GI", value: "Gibraltar" },
  { code: "GN", value: "Guinea" },
  { code: "GP", value: "Guadeloupe" },
  { code: "GM", value: "Gambia" },
  { code: "GW", value: "Guinea-Bissau" },
  { code: "GQ", value: "Equatorial Guinea" },
  { code: "GR", value: "Greece" },
  { code: "GD", value: "Grenada" },
  { code: "GL", value: "Greenland" },
  { code: "GT", value: "Guatemala" },
  { code: "GF", value: "French Guiana" },
  { code: "GU", value: "Guam" },
  { code: "GY", value: "Guyana" },
  { code: "HK", value: "Hong Kong" },
  { code: "HM", value: "Heard Island and McDonald Islands" },
  { code: "HN", value: "Honduras" },
  { code: "HR", value: "Croatia" },
  { code: "HT", value: "Haiti" },
  { code: "HU", value: "Hungary" },
  { code: "ID", value: "Indonesia" },
  { code: "IM", value: "Isle of Man" },
  { code: "IN", value: "India" },
  { code: "IO", value: "British Indian Ocean Territory" },
  { code: "IE", value: "Ireland" },
  { code: "IR", value: "Iran, Islamic Republic of" },
  { code: "IQ", value: "Iraq" },
  { code: "IS", value: "Iceland" },
  { code: "IL", value: "Israel" },
  { code: "IT", value: "Italy" },
  { code: "JM", value: "Jamaica" },
  { code: "JE", value: "Jersey" },
  { code: "JO", value: "Jordan" },
  { code: "JP", value: "Japan" },
  { code: "KZ", value: "Kazakhstan" },
  { code: "KE", value: "Kenya" },
  { code: "KG", value: "Kyrgyzstan" },
  { code: "KH", value: "Cambodia" },
  { code: "KI", value: "Kiribati" },
  { code: "KN", value: "Saint Kitts and Nevis" },
  { code: "KR", value: "Korea, Republic of" },
  { code: "KW", value: "Kuwait" },
  { code: "LA", value: "Lao People's Democratic Republic" },
  { code: "LB", value: "Lebanon" },
  { code: "LR", value: "Liberia" },
  { code: "LY", value: "Libya" },
  { code: "LC", value: "Saint Lucia" },
  { code: "LI", value: "Liechtenstein" },
  { code: "LK", value: "Sri Lanka" },
  { code: "LS", value: "Lesotho" },
  { code: "LT", value: "Lithuania" },
  { code: "LU", value: "Luxembourg" },
  { code: "LV", value: "Latvia" },
  { code: "MO", value: "Macao" },
  { code: "MF", value: "Saint Martin (French part)" },
  { code: "MA", value: "Morocco" },
  { code: "MC", value: "Monaco" },
  { code: "MD", value: "Moldova" },
  { code: "MG", value: "Madagascar" },
  { code: "MV", value: "Maldives" },
  { code: "MX", value: "Mexico" },
  { code: "MH", value: "Marshall Islands" },
  { code: "MK", value: "Macedonia, Republic of" },
  { code: "ML", value: "Mali" },
  { code: "MT", value: "Malta" },
  { code: "MM", value: "Myanmar" },
  { code: "ME", value: "Montenegro" },
  { code: "MN", value: "Mongolia" },
  { code: "MP", value: "Northern Mariana Islands" },
  { code: "MZ", value: "Mozambique" },
  { code: "MR", value: "Mauritania" },
  { code: "MS", value: "Montserrat" },
  { code: "MQ", value: "Martinique" },
  { code: "MU", value: "Mauritius" },
  { code: "MW", value: "Malawi" },
  { code: "MY", value: "Malaysia" },
  { code: "YT", value: "Mayotte" },
  { code: "NA", value: "Namibia" },
  { code: "NC", value: "New Caledonia" },
  { code: "NE", value: "Niger" },
  { code: "NF", value: "Norfolk Island" },
  { code: "NG", value: "Nigeria" },
  { code: "NI", value: "Nicaragua" },
  { code: "NU", value: "Niue" },
  { code: "NL", value: "Netherlands" },
  { code: "NO", value: "Norway" },
  { code: "NP", value: "Nepal" },
  { code: "NR", value: "Nauru" },
  { code: "NZ", value: "New Zealand" },
  { code: "OM", value: "Oman" },
  { code: "PK", value: "Pakistan" },
  { code: "PA", value: "Panama" },
  { code: "PN", value: "Pitcairn" },
  { code: "PE", value: "Peru" },
  { code: "PH", value: "Philippines" },
  { code: "PW", value: "Palau" },
  { code: "PG", value: "Papua New Guinea" },
  { code: "PL", value: "Poland" },
  { code: "PR", value: "Puerto Rico" },
  { code: "KP", value: "Korea, Democratic People's Republic of" },
  { code: "PT", value: "Portugal" },
  { code: "PY", value: "Paraguay" },
  { code: "PS", value: "Palestine, State of" },
  { code: "PF", value: "French Polynesia" },
  { code: "QA", value: "Qatar" },
  { code: "RE", value: "Réunion" },
  { code: "RO", value: "Romania" },
  { code: "RU", value: "Russian Federation" },
  { code: "RW", value: "Rwanda" },
  { code: "SA", value: "Saudi Arabia" },
  { code: "SD", value: "Sudan" },
  { code: "SN", value: "Senegal" },
  { code: "SG", value: "Singapore" },
  { code: "GS", value: "South Georgia and the South Sandwich Islands" },
  { code: "SH", value: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "SJ", value: "Svalbard and Jan Mayen" },
  { code: "SB", value: "Solomon Islands" },
  { code: "SL", value: "Sierra Leone" },
  { code: "SV", value: "El Salvador" },
  { code: "SM", value: "San Marino" },
  { code: "SO", value: "Somalia" },
  { code: "PM", value: "Saint Pierre and Miquelon" },
  { code: "RS", value: "Serbia" },
  { code: "SS", value: "South Sudan" },
  { code: "ST", value: "Sao Tome and Principe" },
  { code: "SR", value: "Suriname" },
  { code: "SK", value: "Slovakia" },
  { code: "SI", value: "Slovenia" },
  { code: "SE", value: "Sweden" },
  { code: "SZ", value: "Swaziland" },
  { code: "SX", value: "Sint Maarten (Dutch part)" },
  { code: "SC", value: "Seychelles" },
  { code: "SY", value: "Syrian Arab Republic" },
  { code: "TC", value: "Turks and Caicos Islands" },
  { code: "TD", value: "Chad" },
  { code: "TG", value: "Togo" },
  { code: "TH", value: "Thailand" },
  { code: "TJ", value: "Tajikistan" },
  { code: "TK", value: "Tokelau" },
  { code: "TM", value: "Turkmenistan" },
  { code: "TL", value: "Timor-Leste" },
  { code: "TO", value: "Tonga" },
  { code: "TT", value: "Trinidad and Tobago" },
  { code: "TN", value: "Tunisia" },
  { code: "TR", value: "Turkey" },
  { code: "TV", value: "Tuvalu" },
  { code: "TW", value: "Taiwan" },
  { code: "TZ", value: "Tanzania" },
  { code: "UG", value: "Uganda" },
  { code: "UA", value: "Ukraine" },
  { code: "UM", value: "United States Minor Outlying Islands" },
  { code: "UY", value: "Uruguay" },
  { code: "US", value: "United States" },
  { code: "UZ", value: "Uzbekistan" },
  { code: "VA", value: "Holy See (Vatican City State)" },
  { code: "VC", value: "Saint Vincent and the Grenadines" },
  { code: "VE", value: "Venezuela" },
  { code: "VG", value: "Virgin Islands, British" },
  { code: "VI", value: "Virgin Islands, U.S." },
  { code: "VN", value: "Vietnam" },
  { code: "VU", value: "Vanuatu" },
  { code: "WF", value: "Wallis and Futuna" },
  { code: "WS", value: "Samoa" },
  { code: "YE", value: "Yemen" },
  { code: "ZA", value: "South Africa" },
  { code: "ZM", value: "Zambia" },
  { code: "ZW", value: "Zimbabwe" }
];

export const businessCategories = [
  "Advertising",
  "Social",
  "Games",
  "Commerce",
  "Blockchain",
  "Electronics and Gadgets",
  "Health and Fitness",
  "Education",
  "Kids",
  "Lifestyle",
  "Banking and Finance",
  "Music",
  "News and Magazines",
  "Travel",
  "Photo and Video",
  "Sports and Outdoors",
  "Productivity",
  "Location-based Business",
  "Others"
];

export const years = [...new Array(100)].map((item, index) => 2010 - index + "");

export const days = [...new Array(31)].map((item, index) => index + 1 + "");

